name: Reusable Workflow - Deploy
#It allows this workflow to be called from other workflows
#This workflows will be kicked off by GitHub Actions whenever a job deploy starts in a 7.ReusableWorkflows yml file
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Output information
        run: echo 'Deploying & uploading'